version: '3.8'

services:
  share_portfolio_backend:
    build:
      context: .
      target: development
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 4000:4000
    env_file:
      - ./.env
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
    command: npm run dev
    depends_on:
      - postgres
    stdin_open: true
    tty: true
    restart: always

  postgres:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_DB: sharesdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123456
    ports:
      - "5436:5432"
    volumes:
      - ${PWD}/app:/var/lib/postgresql/data

  test_db:
    image: postgres
    container_name: test_postgres_db
    environment:
      POSTGRES_DB: sharesdb-test
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123456
    ports:
      - "5433:5432"
    volumes: []

networks:
    default:
      name: share_portfolio_backend