version: '3.8'

services:
  share_portfolio_backend:
    build:
      context: .
      target: production
    env_file:
      - ./.env
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
    depends_on:
      - postgres
