version: '3.8'

services:
  web:
    build:
      context: .
    command: "web-local"
    volumes:
      - ./src:/share-portfolio-backend:delegated
      - ./app_data/web:/share-portfolio-backend/app_data:delegated
    env_file:
      - ./.env
    environment:
      - DATABASE_HOST=db
    depends_on:
      - postgres
    stdin_open: true
    tty: true
    restart: always

  postgres:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_DB: sharesdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123456
    ports:
      - "5436:5436"
    volumes:
      - ${PWD}/app_data:/var/lib/postgresql/data

volumes:
    app_data:

networks:
    default:
      name: web