export const TYPES = {
  InstitutionRepository: Symbol.for('InstitutionRepositoryInterface'),
  MonthlyBalanceRepository: Symbol.for('MonthlyBalanceRepositoryInterface'),
  ShareRepository: Symbol.for('ShareRepositoryInterface'),
  TotalBalanceRepository: Symbol.for('TotalBalanceRepositoryInterface'),
  TransactionRepository: Symbol.for('TransactionRepositoryInterface'),
  InstitutionController: Symbol.for('InstitutionController'),
  TransactionController: Symbol.for('TransactionController'),
  CreateMonthlyBalance: Symbol.for('CreateMonthlyBalance'),
  CreateShare: Symbol.for('CreateShare'),
  CreateTotalBalance: Symbol.for('CreateTotalBalance'),
  CreateTransaction: Symbol.for('AbstractUseCase'),
  GetInstitution: Symbol.for('GetInstitution'),
  GetMonthlyBalance: Symbol.for('GetMonthlyBalance'),
  GetProfit: Symbol.for('GetProfit'),
  GetShare: Symbol.for('GetShare'),
  GetTotalBalance: Symbol.for('GetTotalBalance'),
  UpdateMonthlyBalance: Symbol.for('UpdateMonthlyBalance'),
  UpdatePortfolio: Symbol.for('UpdatePortfolio'),
  UpdateShare: Symbol.for('UpdateShare'),
  UpdateTotalBalance: Symbol.for('UpdateTotalBalance'),
  Database: Symbol.for('Database'),
};
