export const TRANSACTION_TYPE = {
  BUY: 'BUY',
  SELL: 'SELL',
};

export const TRANSACTION_CATEGORY = {
  TRADE: 'TRADE',
  DIVIDENDS: 'DIVIDENDS',
  SPLIT: 'SPLIT',
  BONUS_SHARE: 'BONUS_SHARE',
  OTHER: 'OTHER',
};
